### ISSUE TITLE
Join NFIRS data to Geocoded addresses

### ISSUE THREAD

**Issue by dtromero** [home-fire-risk/smoke_alarm_models#11]
Combine GeoCoded address file with base NFIRS data.

Preliminary understanding of the process to join the data (2013 Example):
2013_geocoded_addresses.csv **> join to >** 2013_formated_addresses.csv **> join to >** nfirs_data 

see: [NFIRS readme.htm](https://drive.google.com/folderview?id=0BxhID98AlD4ZcEg4RmpKd2tPSVE&usp=drive_web&tid=0Bxt-Sxy6HRaxZzhyeFRkUVRvckE#list)

[Google Drive data files](https://drive.google.com/folderview?id=0BxhID98AlD4ZcEg4RmpKd2tPSVE&usp=drive_web&tid=0Bxt-Sxy6HRaxZzhyeFRkUVRvckE#list)

**Comment by brooksandrew** [comment]
@dtromero Feel free to unassign yourself, but I think you already started this, so just wanted to note it, so people know that you're already tackling this one!

**Comment by dtromero** [comment]
Completed task using nfirs_data_blending.py file in 1b model folder.

**Comment by brooksandrew** [comment]
this is great, thanks Daniel!  This should make model_1b_nfirs_smokealarm_pres #12 a lot easier now
