### ISSUE TITLE
model_1b_nfirs_smokealarm_pres

### ISSUE THREAD

**Issue by brooksandrew** [home-fire-risk/smoke_alarm_models#12]
Calculate percent of home fires within county that did not have a smoke alarm installed.  Note there are lots of cases with missing and "U" for Unknown.  What is significance of the missing? Is there any pattern to the missing data?  Prereq to issue #11

**Comment by dracodoc** [comment]
I'm adding my result for this target variable now, including target variable csv, code and documentation files.

**Comment by brooksandrew** [comment]
Awesome, thanks Xianghui, I'm closing this one out and creating a second issue for the model using this target variable.
