### ISSUE TITLE
geocode NFIRS data

### ISSUE THREAD

**Issue by brooksandrew** [home-fire-risk/smoke_alarm_models#2]
geocode NFIRS data acquired via CD-ROM with TIGER geocoder

**Comment by dracodoc** [comment]
I'm uploading geocoded 2010 data by states in [this google drive folder](https://drive.google.com/drive/folders/0BxhID98AlD4ZcEg4RmpKd2tPSVE). Please see the [NFIRS readme.md](https://drive.google.com/file/d/0BxhID98AlD4ZWFBWZmRiZTBWOWs/view?usp=sharing) or [NFIRS readme.html](https://drive.google.com/file/d/0BxhID98AlD4ZcGxjT2R3MzE5TE0/view?usp=sharing)

**Comment by dracodoc** [comment]
2009 ~ 2013 NFIRS data were geocoded and uploaded to google drive folder. Please do not share the data or result publicly per requirement of U.S. Fire Administration.
