### ISSUE TITLE
reverse geocode homevisit data from lat/lon to census tract

### ISSUE THREAD

**Issue by brooksandrew** [home-fire-risk/smoke_alarm_models#7]
home vist data [here](https://drive.google.com/open?id=0Bxt-Sxy6HRaxdWQ5cXlVdDhkemc) on google drive

**Comment by brooksandrew** [comment]
thought i had it made w this service (http://geocoder.maplarge.com/geocoder/reverse), but they geocode first and then make you pay :(

**Comment by hrecht** [comment]
This can be done for free in GIS software (qgis, ArcGIS, etc.) I can run later this week if there are no other takers. Info: http://www.qgistutorials.com/en/docs/performing_spatial_joins.html

**Comment by brooksandrew** [comment]
that looks a lot easier than what i just did (62dc18af6d29ec5d624ee87f9ef969f5102a592c).  i found a [free reverse geocoder API](https://www.fcc.gov/developers/census-block-conversions-api) from the FCC which i ran with... but i only saw ways to do one lat/lon pair at a time, so i messed around with the foreach R package which seems to speed it up quite a bit.
